sudo: false
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install flake8==3.7.9 pylint==2.4.4 black==19.10b0
script:
  - flake8 --exclude cast_channel_pb2.py,authority_keys_pb2.py,logging_pb2.py pychromecast
  - pylint pychromecast
  - black pychromecast --check
